add exception vector definition
apache/teaclave-sgx-sdk pull request #259
Opened 2020-07-21 07:52 UTC by volcano0dr

2020-07-21 08:23 UTC, volcano0dr commented
If CPUID.(EAX=12H, ECX=0):EBX[31:0] != 0, exception vector support GP PF or CP.
Configure `<MiscSelect>1<MiscSelect>` in Enclave.config.xml, encalve can handle GP and PF exceptions.
Tested on CPU: Intel Pentium Silver J5005

2020-07-21 17:22 UTC, dingelish requested changes

2020-07-21 17:22 UTC, dingelish commented on sgx_types/src/types.rs
> +        SGX_EXCEPTION_VECTOR_GP = 13, /* General protectrion exception */
protectrion => protection

2020-07-21 17:22 UTC, dingelish commented on sgx_types/src/types.rs
> +        SGX_EXCEPTION_VECTOR_CP = 21, /* Control protecttion exception */
protection

2020-07-22 03:48 UTC, dingelish approved these changes

2020-07-22 03:49 UTC, merged