Clean up project template
apache/teaclave-sgx-sdk pull request #347
Opened 2021-07-26 15:35 UTC by PiDelport

* Fix spelling / typos
* Avoid hardcoding `SGX_SDK`, so that it can be overridden from the environment

2021-09-13 20:24 UTC, mssun commented on samplecode/project_template/README.md
> +### This is a template project to start developing with the Teaclave Rust SGX SDK (https://github.com/apache/incubator-teaclave-sgx-sdk/) easily.
We call it Teaclave SGX SDK or Rust SGX SDK.

2021-09-13 20:26 UTC, mssun requested changes
I'm okay with the changes. Thank you so much!  I'll merge it if the naming issue are fixed.

2021-09-18 17:49 UTC, PiDelport commented
Cool, change applied: [92a4b6b..c553179](https://github.com/apache/incubator-teaclave-sgx-sdk/compare/92a4b6b..c553179)

2021-09-23 21:23 UTC, merged

2021-09-23 21:23 UTC, mssun commented
Thank you so much! Merged.