First Contribution: Issue #276
apache/teaclave-sgx-sdk pull request #359
Opened 2021-09-11 13:11 UTC by ThomasPluck

- Adjustments to main repo README.md for readability
- Moved existing wiki docs to `/documents` with added permalinks
- Adjusted `/document/README.md` to accomodate all wiki pages
- Removed CSSJ17.pdf and added it as an external cite link

2021-09-12 22:32 UTC, mssun commented
Thanks @ThomasPluck! I'll help to review the PR.

2021-09-13 20:22 UTC, mssun requested changes
Thanks @ThomasPluck. I think we can continue to polish the `README.md`. A lot of things can be improved.

For example, we can put release notes in a separate file. But anyway, this can be done in a follow-up pull request.

2021-09-13 20:22 UTC, mssun commented on Readme.md
> +# Apache Teaclave Rust-SGX SDK
We can formally call it **Teaclave SGX SDK** in all document.

In the introduction, We can say that the project is also called Rust SGX SDK.

2021-09-13 20:22 UTC, mssun commented on Readme.md
> +The Teaclave Rust-SGX SDK helps developers write Intel SGX applications in the Rust programming language. <sup>[[1]](documents/ccsp17.pdf) [[2]](https://dingelish.com/ccs19.pdf)</sup> Please read our
The API docs of Teaclave SGX SDK is hosted in Teaclave's homepage: https://teaclave.apache.org/api-docs/sgx-sdk/sgx_tstd/index.html. I suggest to put this link.

2021-09-13 20:22 UTC, mssun commented on Readme.md
> +To help users understand our project and know how to use it, we are writing some [wiki](https://github.com/apache/teaclave-sgx-sdk/wiki) articles. Please [send me an email](mailto:rustsgx@gmail.com?s
I suggest to abandon the Wiki page, instead use the homepage: https://teaclave.apache.org/sgx-sdk-docs/.

The docs are rendered from files from the `documents` directory automatically.

2021-09-13 20:22 UTC, mssun commented on Readme.md
> +To help users understand our project and know how to use it, we are writing some [wiki](https://github.com/apache/teaclave-sgx-sdk/wiki) articles. Please [send me an email](mailto:rustsgx@gmail.com?s
Since this is an Apache incubating project, any question can be reached at our mailing list: https://teaclave.apache.org/community/#mailing-lists

2021-09-13 20:22 UTC, mssun commented on Readme.md
> +* #### Latest Rust version
Seems that this is not completed? Can you put the specific versions?

2021-09-13 20:22 UTC, mssun commented on Readme.md
>  Yu Ding, dingelish@gmail.com
This can be deleted.

2021-09-13 22:01 UTC, ThomasPluck commented
Added requested changes.

I see we already have a `release_notes.md` already, would you like the release summaries seen in the main `Readme.md` added to these?

2021-09-14 18:42 UTC, mssun commented
> I see we already have a `release_notes.md` already, would you like the release summaries seen in the main `Readme.md` added to these?

I saw you fold the release summary, this is cool. Thanks!

2021-09-14 20:10 UTC, mssun approved these changes
Thanks. I think some docs are some-how out-dated, but I still tend to merge this PR. Then we can polish them later.

2021-09-14 20:11 UTC, merged

2021-09-14 20:31 UTC, mssun commented
The docs are rendered here: https://teaclave.apache.org/sgx-sdk-docs/

All links in the index page are broken because using absolute path. Can you fix it by changing them to relative path?

For example, change `[Setting up your Development Environment](/documents/environment-setup.md)` to `[Setting up your Development Environment](environment-setup.md)`